import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import imageTargetSrc from "@/image/20250424-test target.jpg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "WebAR test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>

      <head>

        <title>test</title>
        <meta itemprop="name" content="test">
        <meta name="twitter:title" content="test">
        <meta property="og:title" content="test">
        <meta property="og:site_name" content="test">
        <meta name="image" content="https://cdn.8thwall.com/apps/cover/default1-preview-1200x630">
        <meta itemprop="image" content="https://cdn.8thwall.com/apps/cover/default1-preview-1200x630">
        <meta property="og:image" content="https://cdn.8thwall.com/apps/cover/default1-preview-1200x630">
        <meta name="twitter:image" content="https://cdn.8thwall.com/apps/cover/default1-preview-1200x630">
      
        <meta property="og:type" content="website">
        <meta name="twitter:card" content="summary_large_image">
        <meta name="8thwall:workspace" content="bkhole">
        <meta name="8thwall:project" content="vps-v2">
        <meta name="8thwall:shortlink" content="zgwg5">

        <script crossorigin="anonymous"
        src="https://cdn.8thwall.com/web/hosting/app8-llffcbpc.js"
        data-xrweb-src="https://apps.8thwall.com/xrweb?appKey=mpwtooqpW8e3Dyl48EgKq9DdkAEbSCF3NyIn1H6BPCWH88VDQnNY1ZuNzrPUbz3ZPqs17i&s=1"
        >
        </script>
        
        <script crossorigin="anonymous" src="//cdn.8thwall.com/web/aframe/8frame-1.4.1.min.js"></script>
        <script crossorigin="anonymous" src="//cdn.8thwall.com/web/xrextras/xrextras.js?s=1"></script>
        <script crossorigin="anonymous" src="//cdn.8thwall.com/web/landing-page/landing-page.js"></script>
        
        <meta name="8thwall:renderer" content="aframe:1.4.1" />
        <meta name="8thwall:package" content="@8thwall.xrextras" />
        <meta name="8thwall:package" content="@8thwall.landing-page" />


        <script
          src="https://code.jquery.com/jquery-3.7.1.min.js"
          integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
          crossorigin="anonymous"></script>

        <script
          src="//cdn.8thwall.com/web/aframe/aframe-extras-7.2.0.min.js"
          crossorigin="anonymous"></script>

        <script src="https://cdn.tailwindcss.com"></script>


      </head>

      <body>
       <div class="absolute left-0 top-0 w-full h-full z-[1000]" id="home-page">
        <Img src="....鄭月妹眼鏡..." alt class="w-full h-full object-cover">
        <div class="absolute left-0 bottom-12 flex w-full items-center justify-center flex-col gap-4">
          <button class="bg-white/20 border border-white text-white backdrop-blur-sm 
          px-4 py-2 rounded-md flex items-center gap-2" id="vps-button">
            <Img src=".............." alt class="w-6 h-6"> 
            "會場使用"
          </button>

          <button class="bg-white/20 border border-white text-white backdrop-blur-sm 
          px-4 py-2 rounded-md flex items-center gap-2" id="vps-button">
            <Img src=".............." alt class="w-6 h-6"> 
            "隨處使用"
          </button>
        </div>
       </div>

       <div class="absolute top-0 left-0 w-full h-full z-10 pointer-events-none" id="pic-preview" style="display: none;">
         <Img src="..............." alt class="absolute top-0 left-0 w-full object-cover" id="pic-top">
         <Img src="..............." alt class="absolute bottom-0 left-0 w-full object-cover" id="pic-bottom">
       </div>

       <div class="absolute left-0 top-0 w-full z-20 pointer-events-none" id="in-scene-page"
       style="display: none;"></div>
       


      </body>
    </html>
  );
}
